# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PC.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QThread, pyqtSignal
import time

class ProgressBarWorker(QThread):   
    
    stop = False
    change_value = pyqtSignal(float)

    def run(self):
        progress = 100
        while progress != 0:
            time.sleep(0.01)
            progress -= 1
            self.change_value.emit(progress)
            if self.stop:
                progress = 0
                break             
        '''
        self.progressBar.show()
        self.progressBar.setProperty("value",100)
        progress = 100
        while progress != 0:
            time.sleep(0.01)
            progress -= 1
            self.progressBar.setProperty("value",progress)
        self.advertising()
        '''

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.image = QtWidgets.QLabel(self.centralwidget)
        self.image.setGeometry(QtCore.QRect(0, 0, 1024, 600))
        self.image.setText("")
        self.image.setPixmap(QtGui.QPixmap("PythonPC/img/resources/systemInfo_dark.jpg"))
        self.image.setObjectName("image")
        self.image.setWindowFlag(QtCore.Qt.CustomizeWindowHint)
        self.barcode = QtWidgets.QLineEdit(self.centralwidget)
        self.barcode.setGeometry(QtCore.QRect(200, 280, 0, 0))
        self.barcode.setObjectName("barcode")       
        self.barcode.textChanged.connect(self.sync_lineEdit)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(10, 570, 1041, 23))
        self.progressBar.setProperty("value", 100)
        self.progressBar.setObjectName("progressBar")
        self.progressBarWorker = ProgressBarWorker()
        self.progressBarThread = QThread()
        self.progressBarWorker.moveToThread(self.progressBarThread)       
        self.progressBarWorker.change_value.connect(self.progressBar.setValue)
        self.progressBarThread.started.connect(self.progressBarWorker.run)       

        MainWindow.setCentralWidget(self.centralwidget)
        self.strrrr()
        
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PriceChecker"))

    def sync_lineEdit(self):
        self.image.setPixmap(QtGui.QPixmap("PythonPC/img/resources/manualInputBc_dark.png"))
        self.barcode.setGeometry(QtCore.QRect(40, 245, 611, 70))

        self.progressBarThread.start()


    def strrrr(self):
        print("ewrwrw")
        f = open("C:/Users/i.talavyria/Desktop/project/Python-PC/PythonPC/Info.txt", "r")
        self.barcode.setText(f.read())

    def advertising(self):
        self.barcode.setText("")
        self.barcode.setGeometry(QtCore.QRect(200, 280, 0, 0))    
        self.image.setPixmap(QtGui.QPixmap("PythonPC/img/resources/systemInfo_dark.jpg"))
        self.progressBar.hide()

        timing = time.time()
        while True:
              if time.time() - timing > 10.0:
                timing = time.time()
                print("10 seconds")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())


